"""add_imagens_profile

Revision ID: 48e09a2d1c5d
Revises: 70681a383ace
Create Date: 2025-01-20 11:12:51.692016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48e09a2d1c5d'
down_revision = '70681a383ace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banner_img_id', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('profile_img_id', sa.Text(), nullable=True))
        batch_op.create_unique_constraint('uq_user_banner_img_id', ['banner_img_id'])
        batch_op.create_unique_constraint('uq_user_profile_img_id', ['profile_img_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_profile_img_id', type_='unique')
        batch_op.drop_constraint('uq_user_banner_img_id', type_='unique')
        batch_op.drop_column('profile_img_id')
        batch_op.drop_column('banner_img_id')

    # ### end Alembic commands ###
