"""add table 'movie'

Revision ID: 560626c475d9
Revises: caa014aa3dfc
Create Date: 2024-01-28 02:18:53.681937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '560626c475d9'
down_revision = 'caa014aa3dfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('original_title', sa.Text(), nullable=False),
    sa.Column('romanised_original_title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('studio', sa.String(length=100), nullable=False),
    sa.Column('director', sa.String(length=100), nullable=False),
    sa.Column('producer', sa.String(length=100), nullable=False),
    sa.Column('rating', sa.Double(), nullable=False),
    sa.Column('banner_img_id', sa.Text(), nullable=False),
    sa.Column('poster_img_id', sa.Text(), nullable=False),
    sa.Column('launch_date', sa.String(length=45), nullable=False),
    sa.Column('running_time', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('banner_img_id'),
    sa.UniqueConstraint('poster_img_id'),
    sa.UniqueConstraint('running_time'),
    sa.UniqueConstraint('studio')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie')
    # ### end Alembic commands ###
