"""relacionamento many to many filme categoria

Revision ID: 70681a383ace
Revises: 6eb475684edf
Create Date: 2025-01-09 00:35:49.444928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70681a383ace'
down_revision = '6eb475684edf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_category',
    sa.Column('movie_id', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('movie_id', 'category_id')
    )
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint('fk_category_movie', type_='foreignkey')
        batch_op.drop_column('movie_id')

    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('release_date', sa.String(length=45), nullable=False))
        batch_op.drop_column('launch_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('launch_date', sa.VARCHAR(length=45), nullable=False))
        batch_op.drop_column('release_date')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movie_id', sa.VARCHAR(), nullable=False))
        batch_op.create_foreign_key('fk_category_movie', 'movie', ['movie_id'], ['id'])

    op.drop_table('movie_category')
    # ### end Alembic commands ###
