"""criando tabela movie_category com mapped

Revision ID: ad6e87a528e9
Revises: 48e09a2d1c5d
Create Date: 2025-01-23 12:13:07.518560

"""
from alembic import op
import sqlalchemy as sa
import app.extensions 


# revision identifiers, used by Alembic.
revision = 'ad6e87a528e9'
down_revision = '48e09a2d1c5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', app.extensions.GUID(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('movie_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('category_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie_category', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('movie_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
